"""add ai appointment recommendation

Revision ID: 8d1a5fc9bddd
Revises: 5c7ed4db19cb
Create Date: 2026-08-07 15:25:54.444723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1a5fc9bddd'
down_revision: Union[str, Sequence[str], None] = '5c7ed4db19cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('suggested_appointment_at', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('suggested_meeting_type', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('appointment_recommendation_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'appointment_recommendation_status')
    op.drop_column('leads', 'suggested_meeting_type')
    op.drop_column('leads', 'suggested_appointment_at')
    # ### end Alembic commands ###
