"""add notes and tags to leads

Revision ID: c5061ea37475
Revises: 9d33c5ee780e
Create Date: 2026-08-05 15:18:40.323299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5061ea37475'
down_revision: Union[str, Sequence[str], None] = '9d33c5ee780e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('leads', sa.Column('tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'tags')
    op.drop_column('leads', 'notes')
    # ### end Alembic commands ###
