"""add ai qualification fields

Revision ID: ffb27066fcd3
Revises: d53016f5a0ca
Create Date: 2026-08-05 02:03:17.817601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb27066fcd3'
down_revision: Union[str, Sequence[str], None] = 'd53016f5a0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('meeting_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column('leads', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('leads', sa.Column('priority', sa.String(length=20), nullable=False, server_default="Medium" ))
    op.add_column('leads', sa.Column('recommended_action', sa.String(length=500), nullable=True))
    op.add_column('leads', sa.Column('follow_up_in_hours', sa.Integer(), nullable=False, server_default="24"))
    op.add_column('leads', sa.Column('ai_reason', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'ai_reason')
    op.drop_column('leads', 'follow_up_in_hours')
    op.drop_column('leads', 'recommended_action')
    op.drop_column('leads', 'priority')
    op.drop_table('appointments')
    # ### end Alembic commands ###
